// Generated by React Router

import 'react-router'

declare module 'react-router' {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  '/': {
    params: {}
  }
  '/parts/:partId': {
    params: {
      partId: string
    }
  }
}

type RouteFiles = {
  'root.tsx': {
    id: 'root'
    page: '/' | '/parts/:partId'
  }
  'routes/home.tsx': {
    id: 'routes/home'
    page: '/'
  }
  'routes/part.tsx': {
    id: 'routes/part'
    page: '/parts/:partId'
  }
}

type RouteModules = {
  root: typeof import('./app/root.tsx')
  'routes/home': typeof import('./app/routes/home.tsx')
  'routes/part': typeof import('./app/routes/part.tsx')
}
